//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracer.Infrastracture.Sql.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookTracer.Infrastracture.Sql.Commands.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS [Authors] (
        ///[Id] TEXT PRIMARY KEY,
        ///[FirstName] TEXT NOT NULL,
        ///[LastName] TEXT NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableAuthors {
            get {
                return ResourceManager.GetString("CreateTableAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS [Books] (
        ///[Id] TEXT PRIMARY KEY,
        ///[Name] TEXT NOT NULL,
        ///[AuthorId] TEXT NOT NULL,
        ///[Rate] INT NOT NULL,
        ///FOREIGN KEY ([AuthorId]) REFERENCES [Authors]([Id]) ON DELETE CASCADE
        ///);.
        /// </summary>
        internal static string CreateTableBooks {
            get {
                return ResourceManager.GetString("CreateTableBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Authors
        ///VALUES (@Id, @FirstName, @LastName).
        /// </summary>
        internal static string InsertAuthor {
            get {
                return ResourceManager.GetString("InsertAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Books
        ///VALUES (@Id, @Name, @AuthorId, @Rate).
        /// </summary>
        internal static string InsertBook {
            get {
                return ResourceManager.GetString("InsertBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Authors
        ///SET [FirstName] = @FirstName, [LastName] = @LastName
        ///WHERE Id = @Id.
        /// </summary>
        internal static string UpdateAuthor {
            get {
                return ResourceManager.GetString("UpdateAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Books
        ///SET [Name] = @Name, [AuthorId] = @AuthorId, [Rate] = @Rate
        ///WHERE [Id] = @Id.
        /// </summary>
        internal static string UpdateBook {
            get {
                return ResourceManager.GetString("UpdateBook", resourceCulture);
            }
        }
    }
}
