//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTracer.Infrastracture.Sql.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookTracer.Infrastracture.Sql.Queries.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///a.[Id] 
        ///, a.[FirstName] 
        ///, a.[LastName]
        ///FROM [Authors] a
        ///--ORDER BY [b].[Name].
        /// </summary>
        internal static string RetrieveAllAuthors {
            get {
                return ResourceManager.GetString("RetrieveAllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///b.[Id] 
        ///, b.[Name] 
        ///, b.[AuthorId]
        ///, b.[Rate]
        ///FROM [Books] b
        ///--ORDER BY [b].[Name].
        /// </summary>
        internal static string RetrieveAllBooks {
            get {
                return ResourceManager.GetString("RetrieveAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///b.[Id] 
        ///, b.[Name] 
        ///, b.[AuthorId]
        ///, b.[Rate]
        ///FROM [Books] b
        ///WHERE [b].[AuthorId] = @AuthorId 
        ///.
        /// </summary>
        internal static string RetrieveBookAuthorId {
            get {
                return ResourceManager.GetString("RetrieveBookAuthorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///b.[Id] 
        ///, b.[Name] 
        ///, b.[AuthorId]
        ///, b.[Rate]
        ///FROM [Books] b
        ///WHERE [b].[Name] = @BookName 
        ///.
        /// </summary>
        internal static string RetrieveByBookName {
            get {
                return ResourceManager.GetString("RetrieveByBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///a.[Id] 
        ///, a.[FirstName] 
        ///, a.[LastName]
        ///FROM [Authors] a
        ///WHERE [a].[FirstName] = @FirstNameValue AND a.[LastName] = @LastNameValue
        ///.
        /// </summary>
        internal static string RetrieveByFirstNameAndLastName {
            get {
                return ResourceManager.GetString("RetrieveByFirstNameAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///a.[Id] 
        ///, a.[FirstName] 
        ///, a.[LastName]
        ///FROM [Authors] a
        ///WHERE [a].[Id] = @Id
        ///.
        /// </summary>
        internal static string RetrieveByGuid {
            get {
                return ResourceManager.GetString("RetrieveByGuid", resourceCulture);
            }
        }
    }
}
